version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    # If you want hot reload during development
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production
      # Add your backend API URL here
      - VITE_API_URL=web-production-e3d6.up.railway.app

    # Optional: only if you want to connect to backend service
    depends_on:
      - web # This should match your Rails service name
